---
.python-default:
  image: python:$PYTHON_VERSION-slim
  tags:
    - linux
  variables:
    POETRY_VERSION: "1.5.*"
    PYTHON_VERSION: "3.11"

.snippets:
  install_poetry:
    - python --version ; pip --version # For debugging
    - pip install poetry==$POETRY_VERSION
    - poetry config virtualenvs.in-project true
    - poetry config installer.max-workers 4
    - poetry --version

stages:
  - test
  - dbt

linting:
  extends: .python-default
  stage: test
  allow_failure: true
  before_script:
    - !reference [.snippets, install_poetry]
    - poetry install
  script:
    - poetry run flake8 duck_f1 --max-line-length=100

tests::unit:
  extends: .python-default
  stage: test
  before_script:
    - !reference [.snippets, install_poetry]
    - poetry install
  script:
    - poetry run coverage run -m pytest tests -v --junitxml=report.xml
    - poetry run coverage xml
    - poetry run coverage report --show-missing --precision=2
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    when: always
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: report.xml

build:
  extends: .python-default
  stage: dbt
  variables:
    DAGSTER_HOME: /tmp/.dagster
    ENV: dev
    OUTPUT_DIR: /tmp/data
    DUCK_DB_PATH: /tmp/data/f1.duckdb
  before_script:
    - !reference [.snippets, install_poetry]
    - poetry install --without dev
    - mkdir /tmp/.dagster
    - poetry run dagster job execute -d duck_f1 -m pipelines -j ergast
    - poetry run dagster job backfill -d duck_f1 -m pipelines -j live_timing --partitions "2020/11/29/race" --noprompt
    - sleep 90
    - cd duck_f1/dbt_duck_f1
  script:
    - poetry run dbt build
