---
name: "dbt_duck_f1"
version: "1.0.0"
config-version: 2

profile: "dbt_duck_f1"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_duck_f1:
    staging:
      +schema: staging
