---
duck_f1:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ./../../../data/f1.duckdb
      schema: ""
      threads: 4
    ci:
      type: duckdb
      path: /tmp/data/f1.duckdb
      schema: ""
      threads: 4
    dist:
      type: duckdb
      path: "{{ var('db_dir') }}/{{ var('db_name') }}.duckdb"
      schema: ""
      threads: 4
