---
name: Update dependencies
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
env:
  PYTHON_VERSION: "3.11"
jobs:
  update-pdm-dependencies:
    name: pdm::update-project
    runs-on: k8s-arc
    permissions:
      contents: write
    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends git
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Update dependencies
        run: |
          pdm update --update-all --save-compatible
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.PAT }}
          commit-message: "chore(deps): update dependencies"
          title: "chore(deps): update project dependencies"
          body: |
            - Dependency updates

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-dependencies
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          committer: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          labels: |
            chore
            dependencies
          assignees: memadore
          reviewers: memadore
