name: dbt project
on:
  pull_request:
jobs:
  Parse:
    runs-on: k8s-arc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pdm install -d
          pdm run dbt deps --project-dir src/duck_f1/transform
      - name: Parse dbt project
        run: |
          pdm run dbt parse \
            --project-dir src/duck_f1/transform \
            --profiles-dir src/duck_f1/transform \
            --vars '{db_dir: "/tmp/data", db_name: "f1"}' \
            --target dist
  Compile:
    runs-on: k8s-arc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"
      - name: Install python dependencies
        run: |
          pdm install -d\
      - name: Prepare dbt project
        run: |
          pdm run dbt deps --project-dir src/duck_f1/transform
          pdm run dbt parse \
            --project-dir src/duck_f1/transform \
            --profiles-dir src/duck_f1/transform \
            --vars '{db_dir: "/tmp/data", db_name: "f1"}' \
            --target dist
      - name: Seed data
        run: pdm run duck-f1 -o /tmp/data run --session-sha eb2f7f20
      - name: Compile project
        run: |
          pdm run dbt compile \
            --project-dir src/duck_f1/transform \
            --profiles-dir src/duck_f1/transform \
            --vars '{db_dir: "/tmp/data", db_name: "f1"}' \
            --target dist
  Docs:
    runs-on: k8s-arc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"
      - name: Install python dependencies
        run: |
          pdm install -d\
      - name: Prepare dbt project
        run: |
          pdm run dbt deps --project-dir src/duck_f1/transform
          pdm run dbt parse \
            --project-dir src/duck_f1/transform \
            --profiles-dir src/duck_f1/transform \
            --vars '{db_dir: "/tmp/data", db_name: "f1"}' \
            --target dist
      - name: Seed data
        run: pdm run duck-f1 -o /tmp/data run --session-sha eb2f7f20
      - name: Generate Docs
        run: |
          poetry run dbt docs generate  \
            --project-dir src/duck_f1/transform \
            --profiles-dir src/duck_f1/transform \
            --vars '{db_dir: "/tmp/data", db_name: "f1"}' \
            --target dist
