name: python package
on: [push]
jobs:
  Linting:
    runs-on: k8s-arc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pdm install -d
      - name: Run tests
        run: |
          pdm run flake8 src/duck_f1 --max-line-length=100
  Tests:
    runs-on: k8s-arc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          pdm install -d
          pdm run dbt deps --project-dir src/duck_f1/transform
          pdm run dbt parse \
            --project-dir src/duck_f1/transform \
            --profiles-dir src/duck_f1/transform \
            --vars '{db_dir: "/tmp/data", db_name: "f1"}' \
            --target dist
      - name: Run tests
        run: |
          pdm run coverage run -m pytest tests -v --junitxml=report.xml
          pdm run coverage xml
          pdm run coverage report --show-missing --precision=2
